name: inferschema
base: core22 
version: '0.1.0' 
summary: infer schema of provided file via Spark's df
description: |
  infer schema of provided file via Spark's df.

adopt-info: inferschema
grade: stable
confinement: strict

architectures:
  - build-on: [amd64]

apps:
  inferschema:
    command: bin/inferschema
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
    plugs: [network, network-bind]

parts:
  inferschema:
    plugin: python
    source: .
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-11-jre-headless
    stage-packages:
      - openjdk-11-jre-headless
    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs