name: inferschema # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: infer schema of provided file via Spark's df # 79 char long summary
description: |
  infer schema of provided file via Spark's df.

adopt-info: inferschema
grade: stable
confinement: strict

architectures:
  - build-on: [amd64]

apps:
  inferschema:
    command: bin/inferschema
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      SPARK_HOME: $SNAP/opt/spark
    plugs: [home, network, network-bind]

parts:
  inferschema:
    after:
    - spark
    plugin: python
    source: .
      
  spark:
    plugin: nil
    build-packages:
      - wget
    stage-packages:
      - openjdk-11-jre-headless
    override-build: |
      wget https://dlcdn.apache.org/spark/spark-3.5.0/spark-3.5.0-bin-hadoop3.tgz
      SPARK_DIR=$CRAFT_PART_INSTALL/opt/spark
      mkdir -p $SPARK_DIR
      tar -zxvf spark-3.5.0-bin-hadoop3.tgz
      mv spark-3.5.0-bin-hadoop3/* $SPARK_DIR/
    override-prime:
      snapcraftctl prime